version: 2
jobs:
  bob:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"

  jake:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Double trouble"
  workflows:
    version: 2
    bob_jake:
      jobs:
        - bob
        - jake 
